name: Update

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  Update_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "date=$(date +%d.%m.%Y)" >> $GITHUB_OUTPUT

    - name: Update lite
      run: |
        pip install -r requirements.txt
        python main.py --lite
    - name: Move lite files
      run: |
        rm -rf lite
        mkdir lite
        mv adhell3_* lite/
    - name: Update
      run: |
        pip install -r requirements.txt
        python main.py
    - name: Update badge in README
      run: |
        sed -i -E "s|img.shields.io/badge/[0-9]{2}\.[0-9]{2}\.[0-9]{4}%20-%20Green\?label=Updated%20at|img.shields.io/badge/${{ steps.date.outputs.date }}%20-%20Green?label=Updated%20at|g" README.md
    - name: Archive file
      uses: actions/upload-artifact@v4
      with:
        name: 'adhell3-components-exodus'
        path: |
          adhell3_activities.txt
          adhell3_providers.txt
          adhell3_receivers.txt
          adhell3_services.txt
          lite/
    - name: Add files and commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Update ${{ steps.date.outputs.date }}'
        add: '.'